/* Do not edit - Machine generated */
#ifndef _INC_REACTOS_BUILDNO
#define _INC_REACTOS_BUILDNO
#define KERNEL_VERSION_BUILD	20040627
#define KERNEL_VERSION_BUILD_STR	"20040627"
#define KERNEL_VERSION_BUILD_RC	"20040627\0"
#define KERNEL_RELEASE_RC	"0.2.3-RELEASE\0"
#define KERNEL_RELEASE_STR	"0.2.3-RELEASE"
#define KERNEL_VERSION_RC	"0.2.3-RELEASE\0"
#define KERNEL_VERSION_STR	"0.2.3-RELEASE"
#endif
/* EOF */
